-- MySQL Script generated by MySQL Workbench
-- Thu Feb  6 12:50:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vault_ddbb
-- -----------------------------------------------------
-- Base de datos de vault_ddbb.

-- -----------------------------------------------------
-- Schema vault_ddbb
--
-- Base de datos de vault_ddbb.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vault_ddbb` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `vault_ddbb` ;

-- -----------------------------------------------------
-- Table `vault_ddbb`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vault_ddbb`.`clients` ;

CREATE TABLE IF NOT EXISTS `vault_ddbb`.`clients` (
  `id_cli_int` INT NULL AUTO_INCREMENT COMMENT 'ID cliente',
  `nom_cli_vch` VARCHAR(100) NOT NULL DEFAULT 'N/A' COMMENT 'Nombre Cliente reemplazando espacios por guion',
  `dat_cli_dat` DATE NULL DEFAULT NOW() COMMENT 'fecha de creación',
  `las_cli_dat` DATE NULL DEFAULT NOW() COMMENT 'fecha de ultima generación de certificado.',
  `lvl_cli_int` INT NULL DEFAULT 1 COMMENT 'Nivel Cliente:\n1- Lectura solo para este cliente.\n2- Escritura solo para este cliente.\n3- Admin, lectura y escritura para todos.',
  PRIMARY KEY (`id_cli_int`),
  UNIQUE INDEX `nom_cli_int_UNIQUE` (`nom_cli_vch` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vault_ddbb`.`params`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vault_ddbb`.`params` ;

CREATE TABLE IF NOT EXISTS `vault_ddbb`.`params` (
  `id_par_int` INT NOT NULL AUTO_INCREMENT COMMENT 'ID Parametro',
  `nom_par_vch` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nombre Parametro',
  `id_cli_int` INT NULL DEFAULT 0 COMMENT 'ID Cliente.',
  `val_par_vch` VARCHAR(344) NULL DEFAULT NULL COMMENT 'Valor parametro.',
  `loc_par_int` INT NULL DEFAULT 1 COMMENT 'ID local del parametro repetido.',
  PRIMARY KEY (`id_par_int`),
  UNIQUE INDEX `id_par_int_UNIQUE` (`id_par_int` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vault_ddbb`.`apis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vault_ddbb`.`apis` ;

CREATE TABLE IF NOT EXISTS `vault_ddbb`.`apis` (
  `id_api_int` INT NOT NULL AUTO_INCREMENT COMMENT 'ID API',
  `id_cli_int` INT NOT NULL COMMENT 'ID Cliente',
  `id_api_vch` VARCHAR(345) NULL COMMENT 'API ID cliente',
  `key_api_vch` VARCHAR(345) NULL COMMENT 'API KEY cliente',
  `dat_api_dat` DATE NULL DEFAULT now() COMMENT 'Fecha creación API ID',
  `mod_api_dat` DATE NULL DEFAULT now() COMMENT 'fecha de modificacion API KEY.\n',
  `loc_api_int` INT NULL DEFAULT 1 COMMENT 'ID loca de API para dejar crear mas de una por cliente.',
  `lvl_api_int` INT NULL DEFAULT 1 COMMENT 'Nivel API:\n1- Lectura solo para este cliente.\n2- Escritura solo para este cliente.\n3- Admin, lectura y escritura para todos.',
  PRIMARY KEY (`id_api_int`),
  UNIQUE INDEX `id_api_int_UNIQUE` (`id_api_int` ASC) VISIBLE)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS change_user;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'change_user' IDENTIFIED BY 'changeme';

GRANT ALL ON `vault_ddbb`.* TO 'change_user';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
